- name: read node ip
  shell:
    cmd: hostname --ip-address
  register: node_ip

- name: install k3s
  shell:
    cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL="{{ k3s_channel }}" INSTALL_K3S_EXEC="--node-ip {{ node_ip.stdout }} --node-external-ip {{ node_ip.stdout }} --flannel-iface eth1" K3S_KUBECONFIG_MODE="0644" sh -

- name: wait for k3s token
  wait_for:
    path: "{{ node_token_location }}"

- name: read k3s token
  slurp:
    path: "{{ node_token_location }}"
  register: node_token

- name: store k3s details
  set_fact:
    k3s_url: "https://{{ node_ip.stdout }}:6443"
    k3s_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: install helm
  shell:
    cmd: curl -sfL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -
