- name: add portainer chart repo
  shell:
    cmd: helm repo add portainer https://portainer.github.io/k8s/

- name: install portainer exposed via load balancer
  shell:
    cmd: helm install --create-namespace -n portainer portainer portainer/portainer --set service.type=LoadBalancer

- name: read node ip
  shell:
    cmd: hostname --ip-address
  register: node_ip

- name: show portainer url
  debug:
    msg: "http://{{ node_ip.stdout }}:9000"